### ISSUE TITLE
🐛채팅 대량의 텍스트 보낸 후 다음 채팅이 안 보내짐

### ISSUE THREAD

**Issue by hyeonheeeee** [100-hours-a-week/10-team-joytas-dao-be#197]
### 🐛 버그 설명

![image](https://github.com/user-attachments/assets/f426c4a9-cd48-4482-b13c-eaa38e24aaf9)
대량의 텍스트를 보낸 직후 다음 채팅 입력시 채팅이 보내지지 않음 

### 🧷 버그 재현 방법

1. 채팅 입장
2. 대량의 텍스트 보내기
3. 다음 채팅 보내기

### 🐋 연관된 이슈

- closed
- resolved

**Comment by junseoparkk** [comment]
HTTP POST 메서드를 통해 메시지를 전송하도록 리팩토링 하였고, 해당 메서드에 스로틀링을 걸어 대량의 텍스트를 보내지 못하도록 수정하였습니다.
